[package]
name = "rust-translate"
version = "0.1.0"
edition = "2021"
description = "A simple Rust crate for text translation between languages."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
